server:
  port: 8181
# Central db configuration
MYSQL_HOST: localhost
DB_NAME: user_management
CONNECTION_PORT: 3306


# Spring datasource configuration
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${CONNECTION_PORT}/${DB_NAME}
    username: root
    password: Root1234&
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  # Hibernate configuration
  #  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update

  spring:
    jpa:
      properties:
        hibernate:
          dialect=org:
            hibernate:
              dialect:
                MySQL8Dialect

  #spring.jpa.show-sql=true
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
