server:
  port: 8181
# Central db configuration
MYSQL_HOST: localhost
DB_NAME: user_management
CONNECTION_PORT: 3306


# Spring datasource configuration
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${CONNECTION_PORT}/${DB_NAME}
    username: root
    password: Root1234&
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  # Hibernate configuration
  #  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update

  spring:
    jpa:
      properties:
        hibernate:
          dialect=org:
            hibernate:
              dialect:
                MySQL8Dialect

  #spring.jpa.show-sql=true
  # Flyway configuration
  #  spring.flyway.baselineOnMigrate=true
  #  spring.flyway.check-location=true
  #  spring.flyway.locations=classpath:db/migration
  #  spring.flyway.schemas=public
  #  spring.flyway.enabled=true

  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true
    locations: classpath:db.migration
    schemas: flyway_schema
#  logging.logback.rollingpolicy.file-name-pattern=${user_management_backend_log}.%d{yyyy-MM-dd}.%i.gz
#logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%
#logging
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  file:
    name: user_management_backend_logs
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway